### ISSUE TITLE
Only works with Python 3.8+

### ISSUE THREAD

**Issue by slochower** [SimonBoothroyd/plotmol#4]
I believe this'll only work with Python 3.8+ due to `Literal`:

```python
ImportError: cannot import name 'Literal' from 'typing' 
```

**Comment by SimonBoothroyd** [comment]
Ah good catch - it turns out this wasn't actually used so I removed it in #6.
